version: "2"

services:
  neo4j:
      image: neo4j:4.4.6
      container_name: "neo4j"
      volumes:
        - ./:/import
      ports:
         - 7474:7474
         - 7687:7687
      environment:
        - NEO4J_AUTH=neo4j/secret
